name: json_logic_dart
description: Build complex rules, serialize them as JSON, and execute them in Dart
version: 0.0.2-nullsafety.0
homepage: https://github.com/ANVLCO/json-logic-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.17.11
