name: json_logic_dart
description: Build complex rules, serialize them as JSON, and execute them in Dart
# version: 1.0.0
# homepage: https://github.com/ANVLCO/json-logic-dart
# author: John Ellis <john@anvl.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
