name: json_logic_dart
description: Build complex rules, serialize them as JSON, and execute them in Dart
version: 0.0.1
homepage: https://github.com/ANVLCO/json-logic-dart

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  kernel: ^0.3.29
  front_end: ^0.1.29
